var h;h||(h=typeof Module !== 'undefined' ? Module : {});var aa=Object.assign({},h),ba=[],ca="./this.program",da=(a,b)=>{throw b;},k="",ea;"undefined"!=typeof document&&document.currentScript&&(k=document.currentScript.src);k=0!==k.indexOf("blob:")?k.substr(0,k.replace(/[?#].*/,"").lastIndexOf("/")+1):"";ea=a=>{document.title=a};var fa=h.print||console.log.bind(console),l=h.printErr||console.warn.bind(console);Object.assign(h,aa);aa=null;h.arguments&&(ba=h.arguments);
h.thisProgram&&(ca=h.thisProgram);h.quit&&(da=h.quit);var ha;h.wasmBinary&&(ha=h.wasmBinary);var noExitRuntime=h.noExitRuntime||!0;"object"!=typeof WebAssembly&&p("no native wasm support detected");var ia,q=!1,ja,u,w,ka,la,x,y,z,A,ma,na=[],oa=[],qa=[],ra=[],sa=[];function ta(){var a=h.preRun.shift();na.unshift(a)}var B=0,ua=null,va=null;function p(a){if(h.onAbort)h.onAbort(a);a="Aborted("+a+")";l(a);q=!0;ja=1;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}
function wa(a){return a.startsWith("data:application/octet-stream;base64,")}var C;C="index.wasm";if(!wa(C)){var xa=C;C=h.locateFile?h.locateFile(xa,k):k+xa}function ya(a){try{if(a==C&&ha)return new Uint8Array(ha);throw"both async and sync fetching of the wasm failed";}catch(b){p(b)}}
function za(a){return ha||"function"!=typeof fetch?Promise.resolve().then(()=>ya(a)):fetch(a,{credentials:"same-origin"}).then(b=>{if(!b.ok)throw"failed to load wasm binary file at '"+a+"'";return b.arrayBuffer()}).catch(()=>ya(a))}function Aa(a,b,c){return za(a).then(d=>WebAssembly.instantiate(d,b)).then(d=>d).then(c,d=>{l("failed to asynchronously prepare wasm: "+d);p(d)})}
function Ba(a,b){var c=C;ha||"function"!=typeof WebAssembly.instantiateStreaming||wa(c)||"function"!=typeof fetch?Aa(c,a,b):fetch(c,{credentials:"same-origin"}).then(d=>WebAssembly.instantiateStreaming(d,a).then(b,function(e){l("wasm streaming compile failed: "+e);l("falling back to ArrayBuffer instantiation");return Aa(c,a,b)}))}
var Ca,Da,Ha={1262240:()=>"undefined"!==typeof AudioContext||"undefined"!==typeof webkitAudioContext?!0:!1,1262387:()=>"undefined"!==typeof navigator.mediaDevices&&"undefined"!==typeof navigator.mediaDevices.getUserMedia||"undefined"!==typeof navigator.webkitGetUserMedia?!0:!1,1262621:a=>{"undefined"===typeof h.SDL2&&(h.SDL2={});var b=h.SDL2;a?b.capture={}:b.audio={};b.$d||("undefined"!==typeof AudioContext?b.$d=new AudioContext:"undefined"!==typeof webkitAudioContext&&(b.$d=new webkitAudioContext),
b.$d&&Ea(b.$d));return void 0===b.$d?-1:0},1263114:()=>h.SDL2.$d.sampleRate,1263182:(a,b,c,d)=>{function e(){}function g(m){void 0!==f.capture.le&&(clearTimeout(f.capture.le),f.capture.le=void 0);f.capture.se=f.$d.createMediaStreamSource(m);f.capture.be=f.$d.createScriptProcessor(b,a,1);f.capture.be.onaudioprocess=function(n){void 0!==f&&void 0!==f.capture&&(n.outputBuffer.getChannelData(0).fill(0),f.capture.ve=n.inputBuffer,Fa(c,[d]))};f.capture.se.connect(f.capture.be);f.capture.be.connect(f.$d.destination);
f.capture.stream=m}var f=h.SDL2;f.capture.te=f.$d.createBuffer(a,b,f.$d.sampleRate);f.capture.te.getChannelData(0).fill(0);f.capture.le=setTimeout(function(){f.capture.ve=f.capture.te;Fa(c,[d])},b/f.$d.sampleRate*1E3);void 0!==navigator.mediaDevices&&void 0!==navigator.mediaDevices.getUserMedia?navigator.mediaDevices.getUserMedia({audio:!0,video:!1}).then(g).catch(e):void 0!==navigator.webkitGetUserMedia&&navigator.webkitGetUserMedia({audio:!0,video:!1},g,e)},1264834:(a,b,c,d)=>{var e=h.SDL2;e.audio.be=
e.$d.createScriptProcessor(b,0,a);e.audio.be.onaudioprocess=function(g){void 0!==e&&void 0!==e.audio&&(e.audio.Be=g.outputBuffer,Fa(c,[d]))};e.audio.be.connect(e.$d.destination)},1265244:(a,b)=>{for(var c=h.SDL2,d=c.capture.ve.numberOfChannels,e=0;e<d;++e){var g=c.capture.ve.getChannelData(e);if(g.length!=b)throw"Web Audio capture buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";if(1==d)for(var f=0;f<b;++f)Ga(a+4*f,g[f]);else for(f=0;f<b;++f)Ga(a+4*(f*d+e),
g[f])}},1265849:(a,b)=>{for(var c=h.SDL2,d=c.audio.Be.numberOfChannels,e=0;e<d;++e){var g=c.audio.Be.getChannelData(e);if(g.length!=b)throw"Web Audio output buffer length mismatch! Destination size: "+g.length+" samples vs expected "+b+" samples!";for(var f=0;f<b;++f)g[f]=z[a+(f*d+e<<2)>>2]}},1266329:a=>{var b=h.SDL2;if(a){void 0!==b.capture.le&&clearTimeout(b.capture.le);if(void 0!==b.capture.stream){a=b.capture.stream.getAudioTracks();for(var c=0;c<a.length;c++)b.capture.stream.removeTrack(a[c]);
b.capture.stream=void 0}void 0!==b.capture.be&&(b.capture.be.onaudioprocess=function(){},b.capture.be.disconnect(),b.capture.be=void 0);void 0!==b.capture.se&&(b.capture.se.disconnect(),b.capture.se=void 0);void 0!==b.capture.te&&(b.capture.te=void 0);b.capture=void 0}else void 0!=b.audio.be&&(b.audio.be.disconnect(),b.audio.be=void 0),b.audio=void 0;void 0!==b.$d&&void 0===b.audio&&void 0===b.capture&&(b.$d.close(),b.$d=void 0)},1267501:(a,b,c)=>{h.SDL2||(h.SDL2={});var d=h.SDL2;d.Le!==h.canvas&&
(d.fe=h.createContext(h.canvas,!1,!0),d.Le=h.canvas);if(d.w!==a||d.Ue!==b||d.We!==d.fe)d.image=d.fe.createImageData(a,b),d.w=a,d.Ue=b,d.We=d.fe;a=d.image.data;b=c>>2;var e=0;if("undefined"!==typeof CanvasPixelArray&&a instanceof CanvasPixelArray)for(c=a.length;e<c;){var g=x[b];a[e]=g&255;a[e+1]=g>>8&255;a[e+2]=g>>16&255;a[e+3]=255;b++;e+=4}else if(d.Oe!==a&&(d.Ne=new Int32Array(a.buffer),d.Pe=new Uint8Array(a.buffer),d.Oe=a),a=d.Ne,c=a.length,a.set(x.subarray(b,b+c)),a=d.Pe,b=3,e=b+4*c,0==c%8)for(;b<
e;)a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0,a[b]=255,b=b+4|0;else for(;b<e;)a[b]=255,b=b+4|0;d.fe.putImageData(d.image,0,0)},1268970:(a,b,c,d,e)=>{var g=document.createElement("canvas");g.width=a;g.height=b;var f=g.getContext("2d");a=f.createImageData(a,b);b=a.data;e>>=2;var m=0,n;if("undefined"!==typeof CanvasPixelArray&&b instanceof CanvasPixelArray)for(n=b.length;m<n;){var r=x[e];b[m]=r&255;b[m+1]=r>>8&255;b[m+2]=r>>
16&255;b[m+3]=r>>24&255;e++;m+=4}else b=new Int32Array(b.buffer),n=b.length,b.set(x.subarray(e,e+n));f.putImageData(a,0,0);c=0===c&&0===d?"url("+g.toDataURL()+"), auto":"url("+g.toDataURL()+") "+c+" "+d+", auto";d=D(c.length+1);E(c,d,c.length+1);return d},1269959:a=>{h.canvas&&(h.canvas.style.cursor=F(a))},1270042:()=>{h.canvas&&(h.canvas.style.cursor="none")},1270111:()=>window.innerWidth,1270141:()=>window.innerHeight};
function Ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}function Ja(a,b,c){a.addEventListener(b,c,{once:!0})}function Ea(a){var b;b||(b=[document,document.getElementById("canvas")]);["keydown","mousedown","touchstart"].forEach(c=>{b.forEach(d=>{d&&Ja(d,c,()=>{"suspended"===a.state&&a.resume()})})})}function Ka(a){for(;0<a.length;)a.shift()(h)}var La=[];function G(a){var b=La[a];b||(a>=La.length&&(La.length=a+1),La[a]=b=ma.get(a));return b}
function Fa(a,b){if("vi".includes("j")){var c=h.dynCall_vi;b&&b.length?c.apply(null,[a].concat(b)):c.call(null,a)}else G(a).apply(null,b)}
function Ga(a,b){var c="float";c.endsWith("*")&&(c="*");switch(c){case "i1":u[a>>0]=b;break;case "i8":u[a>>0]=b;break;case "i16":ka[a>>1]=b;break;case "i32":x[a>>2]=b;break;case "i64":Da=[b>>>0,(Ca=b,1<=+Math.abs(Ca)?0<Ca?+Math.floor(Ca/4294967296)>>>0:~~+Math.ceil((Ca-+(~~Ca>>>0))/4294967296)>>>0:0)];x[a>>2]=Da[0];x[a+4>>2]=Da[1];break;case "float":z[a>>2]=b;break;case "double":A[a>>3]=b;break;case "*":y[a>>2]=b;break;default:p("invalid type for setValue: "+c)}}
var Ma="undefined"!=typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Na(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.buffer&&Ma)return Ma.decode(a.subarray(b,c));for(d="";b<c;){var e=a[b++];if(e&128){var g=a[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var f=a[b++]&63;e=224==(e&240)?(e&15)<<12|g<<6|f:(e&7)<<18|g<<12|f<<6|a[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d}function F(a,b){return a?Na(w,a,b):""}
function Oa(a,b){Pa=a;Qa=b;if(Ra)if(Sa||(Sa=!0),0==a)H=function(){var d=Math.max(0,Ta+b-Ua())|0;setTimeout(Va,d)};else if(1==a)H=function(){Wa(Va)};else if(2==a){if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);setImmediate=function(d){c.push(d);postMessage("setimmediate","*")}}H=function(){setImmediate(Va)}}}var Ua;Ua=()=>performance.now();
function Xa(a,b,c,d,e){!Ra||p("emscripten_set_main_loop: there can only be one main loop function at once: call emscripten_cancel_main_loop to cancel the previous one before setting a new one with different parameters.");Ra=a;Ya=d;var g=Za;Sa=!1;Va=function(){if(!q)if(0<$a.length){var f=Date.now(),m=$a.shift();m.ff(m.bf);if(ab){var n=ab,r=0==n%1?n-1:Math.floor(n);ab=m.df?r:(8*n+(r+.5))/9}fa('main loop blocker "'+m.name+'" took '+(Date.now()-f)+" ms");h.setStatus&&(f=h.statusMessage||"Please wait...",
m=ab,n=bb.ef,m?m<n?h.setStatus(f+" ("+(n-m)+"/"+n+")"):h.setStatus(f):h.setStatus(""));g<Za||setTimeout(Va,0)}else g<Za||(cb=cb+1|0,1==Pa&&1<Qa&&0!=cb%Qa?H():(0==Pa&&(Ta=Ua()),q||h.preMainLoop&&!1===h.preMainLoop()||(db(a),h.postMainLoop&&h.postMainLoop()),g<Za||("object"==typeof SDL&&SDL.audio&&SDL.audio.Ye&&SDL.audio.Ye(),H())))};e||(b&&0<b?Oa(0,1E3/b):Oa(1,1),H());if(c)throw"unwind";}function eb(a){a instanceof Ia||"unwind"==a||da(1,a)}
function fb(a){ja=ja=a;if(!noExitRuntime){if(h.onExit)h.onExit(a);q=!0}da(a,new Ia(a))}function db(a){if(!q)try{if(a(),!noExitRuntime)try{fb(ja)}catch(b){eb(b)}}catch(b){eb(b)}}function gb(a){setTimeout(()=>{db(a)},1E4)}function hb(a){ib||(ib={});ib[a]||(ib[a]=1,l(a))}var ib,Sa=!1,H=null,Za=0,Ra=null,Ya=0,Pa=0,Qa=0,cb=0,$a=[],bb={},Ta,Va,ab,jb=!1,lb=!1,mb=[];
function nb(){function a(){lb=document.pointerLockElement===h.canvas||document.mozPointerLockElement===h.canvas||document.webkitPointerLockElement===h.canvas||document.msPointerLockElement===h.canvas}h.preloadPlugins||(h.preloadPlugins=[]);if(!ob){ob=!0;try{pb=!0}catch(c){pb=!1,l("warning: no blob constructor, cannot create blobs with mimetypes")}qb="undefined"!=typeof MozBlobBuilder?MozBlobBuilder:"undefined"!=typeof WebKitBlobBuilder?WebKitBlobBuilder:pb?null:l("warning: no BlobBuilder");rb="undefined"!=
typeof window?window.URL?window.URL:window.webkitURL:void 0;h.Ee||"undefined"!=typeof rb||(l("warning: Browser does not support creating object URLs. Built-in browser image decoding will not be available."),h.Ee=!0);h.preloadPlugins.push({canHandle:function(c){return!h.Ee&&/\.(jpg|jpeg|png|bmp)$/i.test(c)},handle:function(c,d,e,g){var f=null;if(pb)try{f=new Blob([c],{type:sb(d)}),f.size!==c.length&&(f=new Blob([(new Uint8Array(c)).buffer],{type:sb(d)}))}catch(r){hb("Blob constructor present but fails: "+
r+"; falling back to blob builder")}f||(f=new qb,f.append((new Uint8Array(c)).buffer),f=f.getBlob());var m=rb.createObjectURL(f),n=new Image;n.onload=()=>{n.complete||p("Image "+d+" could not be decoded");var r=document.createElement("canvas");r.width=n.width;r.height=n.height;r.getContext("2d").drawImage(n,0,0);rb.revokeObjectURL(m);e&&e(c)};n.onerror=()=>{fa("Image "+m+" could not be decoded");g&&g()};n.src=m}});h.preloadPlugins.push({canHandle:function(c){return!h.lf&&c.substr(-4)in{".ogg":1,".wav":1,
".mp3":1}},handle:function(c,d,e,g){function f(){n||(n=!0,e&&e(c))}function m(){n||(n=!0,new Audio,g&&g())}var n=!1;if(pb){try{var r=new Blob([c],{type:sb(d)})}catch(v){return m()}r=rb.createObjectURL(r);var t=new Audio;t.addEventListener("canplaythrough",()=>f(t),!1);t.onerror=function(){if(!n){l("warning: browser could not fully decode audio "+d+", trying slower base64 approach");for(var v="",M=0,J=0,pa=0;pa<c.length;pa++)for(M=M<<8|c[pa],J+=8;6<=J;){var kb=M>>J-6&63;J-=6;v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[kb]}2==
J?(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(M&3)<<4],v+="=="):4==J&&(v+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(M&15)<<2],v+="=");t.src="data:audio/x-"+d.substr(-3)+";base64,"+v;f(t)}};t.src=r;gb(()=>{f(t)})}else return m()}});var b=h.canvas;b&&(b.requestPointerLock=b.requestPointerLock||b.mozRequestPointerLock||b.webkitRequestPointerLock||b.msRequestPointerLock||(()=>{}),b.exitPointerLock=document.exitPointerLock||document.mozExitPointerLock||
document.webkitExitPointerLock||document.msExitPointerLock||(()=>{}),b.exitPointerLock=b.exitPointerLock.bind(document),document.addEventListener("pointerlockchange",a,!1),document.addEventListener("mozpointerlockchange",a,!1),document.addEventListener("webkitpointerlockchange",a,!1),document.addEventListener("mspointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",c=>{!lb&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}
function tb(a,b,c,d){if(b&&h.fe&&a==h.canvas)return h.fe;var e;if(b){var g={antialias:!1,alpha:!1,De:1};if(d)for(var f in d)g[f]=d[f];if("undefined"!=typeof ub&&(e=vb(a,g)))var m=I[e].he}else m=a.getContext("2d");if(!m)return null;c&&(b||"undefined"==typeof K||p("cannot set in module if GLctx is used, but we are a non-GL context that would replace it"),h.fe=m,b&&wb(e),h.$e=b,mb.forEach(n=>n()),nb());return m}var xb=!1,yb=void 0,zb=void 0;
function Ab(a,b){function c(){jb=!1;var g=d.parentNode;(document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===g?(d.exitFullscreen=Bb,yb&&d.requestPointerLock(),jb=!0,zb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]|8388608),Cb(h.canvas),Db()):Cb(d)):(g.parentNode.insertBefore(d,g),g.parentNode.removeChild(g),zb?("undefined"!=typeof SDL&&(x[SDL.screen>>2]=y[SDL.screen>>2]&
-8388609),Cb(h.canvas),Db()):Cb(d));if(h.onFullScreen)h.onFullScreen(jb);if(h.onFullscreen)h.onFullscreen(jb)}yb=a;zb=b;"undefined"==typeof yb&&(yb=!0);"undefined"==typeof zb&&(zb=!1);var d=h.canvas;xb||(xb=!0,document.addEventListener("fullscreenchange",c,!1),document.addEventListener("mozfullscreenchange",c,!1),document.addEventListener("webkitfullscreenchange",c,!1),document.addEventListener("MSFullscreenChange",c,!1));var e=document.createElement("div");d.parentNode.insertBefore(e,d);e.appendChild(d);
e.requestFullscreen=e.requestFullscreen||e.mozRequestFullScreen||e.msRequestFullscreen||(e.webkitRequestFullscreen?()=>e.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT):null)||(e.webkitRequestFullScreen?()=>e.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):null);e.requestFullscreen()}
function Bb(){if(!jb)return!1;(document.exitFullscreen||document.cancelFullScreen||document.mozCancelFullScreen||document.msExitFullscreen||document.webkitCancelFullScreen||(()=>{})).apply(document,[]);return!0}var Eb=0;function Wa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===Eb)Eb=b+1E3/60;else for(;b+2>=Eb;)Eb+=1E3/60;setTimeout(a,Math.max(Eb-b,0))}}
function sb(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.substr(a.lastIndexOf(".")+1)]}var Fb=[];function Db(){var a=h.canvas;Fb.forEach(b=>b(a.width,a.height))}
function Cb(a,b,c){b&&c?(a.af=b,a.Ve=c):(b=a.af,c=a.Ve);var d=b,e=c;h.forcedAspectRatio&&0<h.forcedAspectRatio&&(d/e<h.forcedAspectRatio?d=Math.round(e*h.forcedAspectRatio):e=Math.round(d/h.forcedAspectRatio));if((document.fullscreenElement||document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement)===a.parentNode&&"undefined"!=typeof screen){var g=Math.min(screen.width/d,screen.height/e);d=Math.round(d*g);e=Math.round(e*
g)}zb?(a.width!=d&&(a.width=d),a.height!=e&&(a.height=e),"undefined"!=typeof a.style&&(a.style.removeProperty("width"),a.style.removeProperty("height"))):(a.width!=b&&(a.width=b),a.height!=c&&(a.height=c),"undefined"!=typeof a.style&&(d!=b||e!=c?(a.style.setProperty("width",d+"px","important"),a.style.setProperty("height",e+"px","important")):(a.style.removeProperty("width"),a.style.removeProperty("height"))))}
var ob,pb,qb,rb,L=12288,Gb=!1,Hb=0,Ib=0,Jb=0,N={alpha:!1,depth:!1,stencil:!1,antialias:!1},Kb={},Lb;function Mb(a){var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=function(c,d){b.vertexAttribDivisorANGLE(c,d)},a.drawArraysInstanced=function(c,d,e,g){b.drawArraysInstancedANGLE(c,d,e,g)},a.drawElementsInstanced=function(c,d,e,g,f){b.drawElementsInstancedANGLE(c,d,e,g,f)})}
function Nb(a){var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=function(){return b.createVertexArrayOES()},a.deleteVertexArray=function(c){b.deleteVertexArrayOES(c)},a.bindVertexArray=function(c){b.bindVertexArrayOES(c)},a.isVertexArray=function(c){return b.isVertexArrayOES(c)})}function Ob(a){var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=function(c,d){b.drawBuffersWEBGL(c,d)})}var Pb=1,Qb=[],O=[],Rb=[],Sb=[],Tb=[],P=[],Ub=[],I=[],Q=[],Vb={},Wb=4;
function R(a){Xb||(Xb=a)}function Yb(a){for(var b=Pb++,c=a.length;c<b;c++)a[c]=null;return b}function vb(a,b){a.ne||(a.ne=a.getContext,a.getContext=function(d,e){e=a.ne(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=a.getContext("webgl",b);return c?Zb(c,b):0}function Zb(a,b){var c=Yb(I),d={gf:c,attributes:b,version:b.De,he:a};a.canvas&&(a.canvas.ke=d);I[c]=d;("undefined"==typeof b.Re||b.Re)&&$b(d);return c}function wb(a){ac=I[a];h.fe=K=ac&&ac.he}
function $b(a){a||(a=ac);if(!a.Xe){a.Xe=!0;var b=a.he;Mb(b);Nb(b);Ob(b);b.ge=b.getExtension("EXT_disjoint_timer_query");b.kf=b.getExtension("WEBGL_multi_draw");(b.getSupportedExtensions()||[]).forEach(function(c){c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}}var ub={},Xb,ac;function bc(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b}
function E(a,b,c){var d=w;if(!(0<c))return 0;var e=b;c=b+c-1;for(var g=0;g<a.length;++g){var f=a.charCodeAt(g);if(55296<=f&&57343>=f){var m=a.charCodeAt(++g);f=65536+((f&1023)<<10)|m&1023}if(127>=f){if(b>=c)break;d[b++]=f}else{if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6}else{if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63}d[b++]=128|f>>6&63}d[b++]=128|f&63}}d[b]=0;return b-e}function S(a){var b=bc(a)+1,c=D(b);c&&E(a,c,b);return c}var cc=[];
function dc(a,b){cc.length=0;var c;for(b>>=2;c=w[a++];)b+=105!=c&b,cc.push(105==c?x[b]:A[b++>>1]),++b;return cc}function ec(a){var b=fc();a=a();gc(b);return a}var hc=0;function ic(){for(var a=T.length-1;0<=a;--a)jc(a);T=[];U=[]}var U=[];function kc(a,b,c){function d(f,m){if(f.length!=m.length)return!1;for(var n in f)if(f[n]!=m[n])return!1;return!0}for(var e in U){var g=U[e];if(g.xe==a&&d(g.ze,c))return}U.push({xe:a,Ge:b,ze:c});U.sort(function(f,m){return f.Ge<m.Ge})}
function lc(a){for(var b=0;b<U.length;++b)U[b].xe==a&&(U.splice(b,1),--b)}function mc(){if(hc&&nc.je)for(var a=0;a<U.length;++a){var b=U[a];U.splice(a,1);--a;b.xe.apply(null,b.ze)}}var T=[];function jc(a){var b=T[a];b.target.removeEventListener(b.ae,b.Se,b.ce);T.splice(a,1)}
function V(a){function b(d){++hc;nc=a;mc();a.ee(d);mc();--hc}if(a.de)a.Se=b,a.target.addEventListener(a.ae,b,a.ce),T.push(a),oc||(ra.push(ic),oc=!0);else for(var c=0;c<T.length;++c)T[c].target==a.target&&T[c].ae==a.ae&&jc(c--)}function pc(a){return a?a==window?"#window":a==screen?"#screen":a&&a.nodeName?a.nodeName:"":""}function qc(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}var rc={},oc,nc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec={},Fc=[0,document,window];
function W(a){a=2<a?F(a):a;return Fc[a]||document.querySelector(a)}function Gc(a){var b=bc(a)+1,c=Hc(b);E(a,c,b);return c}function Ic(a){return ec(function(){var b=Hc(8),c=b+4,d=Gc(a.id);if(d=W(d))x[b>>2]=d.width,x[c>>2]=d.height;return[x[b>>2],x[c>>2]]})}function Jc(a,b,c){a=W(a);if(!a)return-4;a.width=b;a.height=c;return 0}function Kc(a,b,c){a.cf?ec(function(){var d=Gc(a.id);Jc(d,b,c)}):(a.width=b,a.height=c)}
function Lc(a){function b(){document.fullscreenElement||document.webkitFullscreenElement||(document.removeEventListener("fullscreenchange",b),document.removeEventListener("webkitfullscreenchange",b),Kc(a,d,e),a.style.width=g,a.style.height=f,a.style.backgroundColor=m,n||(document.body.style.backgroundColor="white"),document.body.style.backgroundColor=n,a.style.paddingLeft=r,a.style.paddingRight=t,a.style.paddingTop=v,a.style.paddingBottom=M,a.style.marginLeft=J,a.style.marginRight=pa,a.style.marginTop=
kb,a.style.marginBottom=Sd,document.body.style.margin=Td,document.documentElement.style.overflow=Ud,document.body.scroll=Vd,a.style.ie=Wd,a.ke&&a.ke.he.viewport(0,0,d,e),Ec.oe&&G(Ec.oe)(37,0,Ec.Ae))}var c=Ic(a),d=c[0],e=c[1],g=a.style.width,f=a.style.height,m=a.style.backgroundColor,n=document.body.style.backgroundColor,r=a.style.paddingLeft,t=a.style.paddingRight,v=a.style.paddingTop,M=a.style.paddingBottom,J=a.style.marginLeft,pa=a.style.marginRight,kb=a.style.marginTop,Sd=a.style.marginBottom,
Td=document.body.style.margin,Ud=document.documentElement.style.overflow,Vd=document.body.scroll,Wd=a.style.ie;document.addEventListener("fullscreenchange",b);document.addEventListener("webkitfullscreenchange",b)}function Mc(a,b,c){a.style.paddingLeft=a.style.paddingRight=c+"px";a.style.paddingTop=a.style.paddingBottom=b+"px"}function Nc(a){return 0>Fc.indexOf(a)?a.getBoundingClientRect():{left:0,top:0}}
function Oc(a,b){if(0!=b.we||0!=b.ue){Lc(a);var c=b.Ze?innerWidth:screen.width,d=b.Ze?innerHeight:screen.height,e=Nc(a),g=e.width;e=e.height;var f=Ic(a),m=f[0];f=f[1];3==b.we?(Mc(a,(d-e)/2,(c-g)/2),c=g,d=e):2==b.we&&(c*f<m*d?(g=f*c/m,Mc(a,(d-g)/2,0),d=g):(g=m*d/f,Mc(a,0,(c-g)/2),c=g));a.style.backgroundColor||(a.style.backgroundColor="black");document.body.style.backgroundColor||(document.body.style.backgroundColor="black");a.style.width=c+"px";a.style.height=d+"px";1==b.Te&&(a.style.ie="optimizeSpeed",
a.style.ie="-moz-crisp-edges",a.style.ie="-o-crisp-edges",a.style.ie="-webkit-optimize-contrast",a.style.ie="optimize-contrast",a.style.ie="crisp-edges",a.style.ie="pixelated");g=2==b.ue?devicePixelRatio:1;0!=b.ue&&(c=c*g|0,d=d*g|0,Kc(a,c,d),a.ke&&a.ke.he.viewport(0,0,c,d))}if(a.requestFullscreen)a.requestFullscreen();else if(a.webkitRequestFullscreen)a.webkitRequestFullscreen(Element.ALLOW_KEYBOARD_INPUT);else return qc()?-3:-1;Ec=b;b.oe&&G(b.oe)(37,0,b.Ae);return 0}
function Pc(a){if(a.requestPointerLock)a.requestPointerLock();else return document.body.requestPointerLock?-3:-1;return 0}
function Qc(a,b){A[a>>3]=b.timestamp;for(var c=0;c<b.axes.length;++c)A[a+8*c+16>>3]=b.axes[c];for(c=0;c<b.buttons.length;++c)A[a+8*c+528>>3]="object"==typeof b.buttons[c]?b.buttons[c].value:b.buttons[c];for(c=0;c<b.buttons.length;++c)x[a+4*c+1040>>2]="object"==typeof b.buttons[c]?b.buttons[c].pressed:1==b.buttons[c];x[a+1296>>2]=b.connected;x[a+1300>>2]=b.index;x[a+8>>2]=b.axes.length;x[a+12>>2]=b.buttons.length;E(b.id,a+1304,64);E(b.mapping,a+1368,64)}function Rc(a,b){K.attachShader(O[a],P[b])}
function Sc(a,b){K.bindBuffer(a,Qb[b])}function Tc(a,b,c,d){K.bufferData(a,c?w.subarray(c,c+b):b,d)}function Uc(a){K.clear(a)}function Vc(a,b,c,d){K.clearColor(a,b,c,d)}function Wc(a){K.compileShader(P[a])}function Xc(){var a=Yb(O),b=K.createProgram();b.name=a;b.re=b.pe=b.qe=0;b.ye=1;O[a]=b;return a}function Yc(a){var b=Yb(P);P[b]=K.createShader(a);return b}function Zc(a){if(a){var b=O[a];b?(K.deleteProgram(b),b.name=0,O[a]=null):R(1281)}}var $c=[];function ad(a,b,c,d){K.drawElements(a,b,c,d)}
function bd(a){K.enable(a)}function cd(a){K.enableVertexAttribArray(a)}function dd(a,b,c,d){for(var e=0;e<a;e++){var g=K[c](),f=g&&Yb(d);g?(g.name=f,d[f]=g):R(1282);x[b+4*e>>2]=f}}function ed(a,b){dd(a,b,"createBuffer",Qb)}function fd(a,b,c,d,e,g,f,m){b=O[b];if(a=K[a](b,c))d=m&&E(a.name,m,d),e&&(x[e>>2]=d),g&&(x[g>>2]=a.size),f&&(x[f>>2]=a.type)}function gd(a,b){return K.getAttribLocation(O[a],F(b))}function hd(a,b){y[a>>2]=b;y[a+4>>2]=(b-y[a>>2])/4294967296}
function jd(a,b,c){if(b){var d=void 0;switch(a){case 36346:d=1;break;case 36344:0!=c&&1!=c&&R(1280);return;case 36345:d=0;break;case 34466:var e=K.getParameter(34467);d=e?e.length:0}if(void 0===d)switch(e=K.getParameter(a),typeof e){case "number":d=e;break;case "boolean":d=e?1:0;break;case "string":R(1280);return;case "object":if(null===e)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 34068:d=0;break;default:R(1280);return}else{if(e instanceof Float32Array||
e instanceof Uint32Array||e instanceof Int32Array||e instanceof Array){for(a=0;a<e.length;++a)switch(c){case 0:x[b+4*a>>2]=e[a];break;case 2:z[b+4*a>>2]=e[a];break;case 4:u[b+a>>0]=e[a]?1:0}return}try{d=e.name|0}catch(g){R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Unknown object returned from WebGL getParameter("+a+")! (error: "+g+")");return}}break;default:R(1280);l("GL_INVALID_ENUM in glGet"+c+"v: Native code calling glGet"+c+"v("+a+") and it returns "+e+" of type "+typeof e+"!");return}switch(c){case 1:hd(b,
d);break;case 0:x[b>>2]=d;break;case 2:z[b>>2]=d;break;case 4:u[b>>0]=d?1:0}}else R(1281)}function kd(a,b,c,d){a=K.getProgramInfoLog(O[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(x[c>>2]=b)}
function ld(a,b,c){if(c)if(a>=Pb)R(1281);else if(a=O[a],35716==b)a=K.getProgramInfoLog(a),null===a&&(a="(unknown error)"),x[c>>2]=a.length+1;else if(35719==b){if(!a.re)for(b=0;b<K.getProgramParameter(a,35718);++b)a.re=Math.max(a.re,K.getActiveUniform(a,b).name.length+1);x[c>>2]=a.re}else if(35722==b){if(!a.pe)for(b=0;b<K.getProgramParameter(a,35721);++b)a.pe=Math.max(a.pe,K.getActiveAttrib(a,b).name.length+1);x[c>>2]=a.pe}else if(35381==b){if(!a.qe)for(b=0;b<K.getProgramParameter(a,35382);++b)a.qe=
Math.max(a.qe,K.getActiveUniformBlockName(a,b).length+1);x[c>>2]=a.qe}else x[c>>2]=K.getProgramParameter(a,b);else R(1281)}function md(a,b,c){if(c){a=K.ge.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;hd(c,d)}else R(1281)}function nd(a,b,c){if(c){a=K.ge.getQueryObjectEXT(Q[a],b);var d;"boolean"==typeof a?d=a?1:0:d=a;x[c>>2]=d}else R(1281)}function od(a){return"]"==a.slice(-1)&&a.lastIndexOf("[")}
function pd(a){var b=a.me,c=a.Ie,d;if(!b)for(a.me=b={},a.He={},d=0;d<K.getProgramParameter(a,35718);++d){var e=K.getActiveUniform(a,d);var g=e.name;e=e.size;var f=od(g);f=0<f?g.slice(0,f):g;var m=a.ye;a.ye+=e;c[f]=[e,m];for(g=0;g<e;++g)b[m]=g,a.He[m++]=f}}function qd(a,b){b=F(b);if(a=O[a]){pd(a);var c=a.me,d=0,e=b,g=od(b);0<g&&(d=parseInt(b.slice(g+1))>>>0,e=b.slice(0,g));if((e=a.Ie[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||K.getUniformLocation(a,b)))return d}else R(1281);return-1}
function X(a){var b=K.Me;if(b){var c=b.me[a];"number"==typeof c&&(b.me[a]=c=K.getUniformLocation(b,b.He[a]+(0<c?"["+c+"]":"")));return c}R(1282)}function rd(a,b,c,d){if(c)if(a=O[a],pd(a),a=K.getUniform(a,X(b)),"number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b]}else R(1281)}
function sd(a,b,c,d){if(c)if(a=K.getVertexAttrib(a,b),34975==b)x[c>>2]=a&&a.name;else if("number"==typeof a||"boolean"==typeof a)switch(d){case 0:x[c>>2]=a;break;case 2:z[c>>2]=a;break;case 5:x[c>>2]=Math.fround(a)}else for(b=0;b<a.length;b++)switch(d){case 0:x[c+4*b>>2]=a[b];break;case 2:z[c+4*b>>2]=a[b];break;case 5:x[c+4*b>>2]=Math.fround(a[b])}else R(1281)}function td(a){a=O[a];K.linkProgram(a);a.me=0;a.Ie={}}
function ud(a,b,c,d,e){a-=5120;a=1==a?w:4==a?x:6==a?z:5==a||28922==a?y:la;var g=31-Math.clz32(a.BYTES_PER_ELEMENT),f=Wb;return a.subarray(e>>g,e+d*(c*({5:3,6:4,8:2,29502:3,29504:4}[b-6402]||1)*(1<<g)+f-1&-f)>>g)}function vd(a,b,c,d){for(var e="",g=0;g<b;++g){var f=d?x[d+4*g>>2]:-1;e+=F(x[c+4*g>>2],0>f?void 0:f)}K.shaderSource(P[a],e)}function wd(a,b){K.uniform1f(X(a),b)}var Y=[],xd=[];function yd(a,b,c,d){K.uniform3f(X(a),b,c,d)}
function zd(a,b,c,d){if(18>=b){var e=Y[16*b-1],g=z;d>>=2;for(var f=0;f<16*b;f+=16){var m=d+f;e[f]=g[m];e[f+1]=g[m+1];e[f+2]=g[m+2];e[f+3]=g[m+3];e[f+4]=g[m+4];e[f+5]=g[m+5];e[f+6]=g[m+6];e[f+7]=g[m+7];e[f+8]=g[m+8];e[f+9]=g[m+9];e[f+10]=g[m+10];e[f+11]=g[m+11];e[f+12]=g[m+12];e[f+13]=g[m+13];e[f+14]=g[m+14];e[f+15]=g[m+15]}}else e=z.subarray(d>>2,d+64*b>>2);K.uniformMatrix4fv(X(a),!!c,e)}function Ad(a){a=O[a];K.useProgram(a);K.Me=a}function Bd(a,b,c,d,e,g){K.vertexAttribPointer(a,b,c,!!d,e,g)}
function Cd(a,b,c,d){K.viewport(a,b,c,d)}function Dd(a,b){if(!qc())return-1;a=W(a);return a?a.requestFullscreen||a.webkitRequestFullscreen?hc&&nc.je?Oc(a,b):b.Qe?(kc(Oc,1,[a,b]),1):-2:-3:-4}function Ed(a,b){var c={target:W(2),ae:"beforeunload",de:b,ee:function(d=event){var e=G(b)(28,0,a);e&&(e=F(e));if(e)return d.preventDefault(),d.returnValue=e},ce:!0};V(c)}
function Fd(a,b,c,d,e,g){tc||(tc=D(256));a={target:W(a),ae:g,de:d,ee:function(f=event){var m=f.target.id?f.target.id:"",n=tc;E(pc(f.target),n+0,128);E(m,n+128,128);G(d)(e,n,b)&&f.preventDefault()},ce:c};V(a)}
function Gd(a,b,c,d,e){vc||(vc=D(280));V({target:a,ae:e,de:d,ee:function(g=event){var f=vc,m=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.msFullscreenElement,n=!!m;x[f>>2]=n;x[f+4>>2]=qc();var r=n?m:uc,t=r&&r.id?r.id:"";E(pc(r),f+8,128);E(t,f+136,128);x[f+264>>2]=r?r.clientWidth:0;x[f+268>>2]=r?r.clientHeight:0;x[f+272>>2]=screen.width;x[f+276>>2]=screen.height;n&&(uc=m);G(d)(19,f,b)&&g.preventDefault()},ce:c})}
function Hd(a,b,c,d,e){wc||(wc=D(1432));b={target:W(2),je:!0,ae:e,de:c,ee:function(g=event){var f=wc;Qc(f,g.gamepad);G(c)(d,f,a)&&g.preventDefault()},ce:b};V(b)}
function Id(a,b,c,d,e,g){xc||(xc=D(176));a={target:W(a),je:!0,ae:g,de:d,ee:function(f){var m=xc;A[m>>3]=f.timeStamp;var n=m>>2;x[n+2]=f.location;x[n+3]=f.ctrlKey;x[n+4]=f.shiftKey;x[n+5]=f.altKey;x[n+6]=f.metaKey;x[n+7]=f.repeat;x[n+8]=f.charCode;x[n+9]=f.keyCode;x[n+10]=f.which;E(f.key||"",m+44,32);E(f.code||"",m+76,32);E(f.char||"",m+108,32);E(f.locale||"",m+140,32);G(d)(e,m,b)&&f.preventDefault()},ce:c};V(a)}
function Jd(a,b,c){A[a>>3]=b.timeStamp;a>>=2;x[a+2]=b.screenX;x[a+3]=b.screenY;x[a+4]=b.clientX;x[a+5]=b.clientY;x[a+6]=b.ctrlKey;x[a+7]=b.shiftKey;x[a+8]=b.altKey;x[a+9]=b.metaKey;ka[2*a+20]=b.button;ka[2*a+21]=b.buttons;x[a+11]=b.movementX;x[a+12]=b.movementY;c=Nc(c);x[a+13]=b.clientX-c.left;x[a+14]=b.clientY-c.top}
function Kd(a,b,c,d,e,g){yc||(yc=D(72));a=W(a);V({target:a,je:"mousemove"!=g&&"mouseenter"!=g&&"mouseleave"!=g,ae:g,de:d,ee:function(f=event){Jd(yc,f,a);G(d)(e,yc,b)&&f.preventDefault()},ce:c})}function Ld(a,b,c,d,e){zc||(zc=D(260));V({target:a,ae:e,de:d,ee:function(g=event){var f=zc,m=document.pointerLockElement||document.ne||document.Ke||document.Je;x[f>>2]=!!m;var n=m&&m.id?m.id:"";E(pc(m),f+4,128);E(n,f+132,128);G(d)(20,f,b)&&g.preventDefault()},ce:c})}
function Md(a,b,c,d){Ac||(Ac=D(36));a=W(a);V({target:a,ae:"resize",de:d,ee:function(e=event){if(e.target==a){var g=document.body;if(g){var f=Ac;x[f>>2]=e.detail;x[f+4>>2]=g.clientWidth;x[f+8>>2]=g.clientHeight;x[f+12>>2]=innerWidth;x[f+16>>2]=innerHeight;x[f+20>>2]=outerWidth;x[f+24>>2]=outerHeight;x[f+28>>2]=pageXOffset;x[f+32>>2]=pageYOffset;G(d)(10,f,b)&&e.preventDefault()}}},ce:c})}
function Nd(a,b,c,d,e,g){Bc||(Bc=D(1696));a=W(a);V({target:a,je:"touchstart"==g||"touchend"==g,ae:g,de:d,ee:function(f){for(var m,n={},r=f.touches,t=0;t<r.length;++t)m=r[t],m.Ce=m.Fe=0,n[m.identifier]=m;for(t=0;t<f.changedTouches.length;++t)m=f.changedTouches[t],m.Ce=1,n[m.identifier]=m;for(t=0;t<f.targetTouches.length;++t)n[f.targetTouches[t].identifier].Fe=1;r=Bc;A[r>>3]=f.timeStamp;var v=r>>2;x[v+3]=f.ctrlKey;x[v+4]=f.shiftKey;x[v+5]=f.altKey;x[v+6]=f.metaKey;v+=7;var M=Nc(a),J=0;for(t in n)if(m=
n[t],x[v]=m.identifier,x[v+1]=m.screenX,x[v+2]=m.screenY,x[v+3]=m.clientX,x[v+4]=m.clientY,x[v+5]=m.pageX,x[v+6]=m.pageY,x[v+7]=m.Ce,x[v+8]=m.Fe,x[v+9]=m.clientX-M.left,x[v+10]=m.clientY-M.top,v+=13,31<++J)break;x[r+8>>2]=J;G(d)(e,r,b)&&f.preventDefault()},ce:c})}
function Od(a,b,c){var d=Fc[1];Cc||(Cc=D(8));V({target:d,ae:"visibilitychange",de:c,ee:function(e=event){var g=Cc,f=["hidden","visible","prerender","unloaded"].indexOf(document.visibilityState);x[g>>2]=document.hidden;x[g+4>>2]=f;G(c)(21,g,a)&&e.preventDefault()},ce:b})}
function Pd(a,b,c,d){Dc||(Dc=D(104));V({target:a,je:!0,ae:"wheel",de:d,ee:function(e=event){var g=Dc;Jd(g,e,a);A[g+72>>3]=e.deltaX;A[g+80>>3]=e.deltaY;A[g+88>>3]=e.deltaZ;x[g+96>>2]=e.deltaMode;G(d)(9,g,b)&&e.preventDefault()},ce:c})}var Qd={};
function Rd(){if(!Xd){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"==typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Qd)void 0===Qd[b]?delete a[b]:a[b]=Qd[b];var c=[];for(b in a)c.push(b+"="+a[b]);Xd=c}return Xd}var Xd,Yd=[null,[],[]];h.requestFullscreen=function(a,b){Ab(a,b)};h.requestAnimationFrame=function(a){Wa(a)};
h.setCanvasSize=function(a,b,c){Cb(h.canvas,a,b);c||Db()};h.pauseMainLoop=function(){H=null;Za++};h.resumeMainLoop=function(){Za++;var a=Pa,b=Qa,c=Ra;Ra=null;Xa(c,0,!1,Ya,!0);Oa(a,b);H()};h.getUserMedia=function(){window.getUserMedia||(window.getUserMedia=navigator.getUserMedia||navigator.mozGetUserMedia);window.getUserMedia(void 0)};h.createContext=function(a,b,c,d){return tb(a,b,c,d)};for(var K,Z=0;32>Z;++Z)$c.push(Array(Z));var Zd=new Float32Array(288);for(Z=0;288>Z;++Z)Y[Z]=Zd.subarray(0,Z+1);
var $d=new Int32Array(288);for(Z=0;288>Z;++Z)xd[Z]=$d.subarray(0,Z+1);
var ae={S:function(){return 0},Va:function(){return 0},Xa:function(){},Ya:function(){return!0},Fa:function(a){if(12448==a)return L=12288,1;L=12300;return 0},Ia:function(a,b,c,d,e){if(62E3!=a)L=12296,c=0;else{if(b)for(;;){a=x[b>>2];if(12321==a)N.alpha=0<x[b+4>>2];else if(12325==a)N.depth=0<x[b+4>>2];else if(12326==a)N.stencil=0<x[b+4>>2];else if(12337==a)a=x[b+4>>2],N.antialias=0<a;else if(12338==a)a=x[b+4>>2],N.antialias=1==a;else if(12544==a)N.hf=12547!=x[b+4>>2];else if(12344==a)break;b+=8}c&&d||
e?(e&&(x[e>>2]=1),c&&0<d&&(x[c>>2]=62002),L=12288,c=1):(L=12300,c=0)}return c},va:function(a,b,c,d){if(62E3!=a)return L=12296,0;for(a=1;;){b=x[d>>2];if(12440==b)a=x[d+4>>2];else if(12344==b)break;else return L=12292,0;d+=8}if(2!=a)return L=12293,0;N.De=a-1;N.jf=0;Lb=vb(h.canvas,N);if(0!=Lb)return L=12288,wb(Lb),h.$e=!0,mb.forEach(function(e){e()}),wb(null),62004;L=12297;return 0},xa:function(a,b){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;L=12288;return 62006},wa:function(a,b){if(62E3!=
a)return L=12296,0;if(62004!=b)return L=12294,0;a=Lb;ac===I[a]&&(ac=null);if("object"==typeof rc)for(var c=I[a].he.canvas,d=0;d<T.length;++d)T[d].target!=c||jc(d--);I[a]&&I[a].he.canvas&&(I[a].he.canvas.ke=void 0);I[a]=null;L=12288;Hb==b&&(Hb=0);return 1},ya:function(a,b){if(62E3!=a)return L=12296,0;if(62006!=b)return L=12301,1;Ib==b&&(Ib=0);Jb==b&&(Jb=0);L=12288;return 1},Ka:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(62002!=b)return L=12293,0;if(!d)return L=12300,0;L=12288;switch(c){case 12320:return x[d>>
2]=N.alpha?32:24,1;case 12321:return x[d>>2]=N.alpha?8:0,1;case 12322:return x[d>>2]=8,1;case 12323:return x[d>>2]=8,1;case 12324:return x[d>>2]=8,1;case 12325:return x[d>>2]=N.depth?24:0,1;case 12326:return x[d>>2]=N.stencil?8:0,1;case 12327:return x[d>>2]=12344,1;case 12328:return x[d>>2]=62002,1;case 12329:return x[d>>2]=0,1;case 12330:return x[d>>2]=4096,1;case 12331:return x[d>>2]=16777216,1;case 12332:return x[d>>2]=4096,1;case 12333:return x[d>>2]=0,1;case 12334:return x[d>>2]=0,1;case 12335:return x[d>>
2]=12344,1;case 12337:return x[d>>2]=N.antialias?4:0,1;case 12338:return x[d>>2]=N.antialias?1:0,1;case 12339:return x[d>>2]=4,1;case 12340:return x[d>>2]=12344,1;case 12341:case 12342:case 12343:return x[d>>2]=-1,1;case 12345:case 12346:return x[d>>2]=0,1;case 12347:return x[d>>2]=0,1;case 12348:return x[d>>2]=1;case 12349:case 12350:return x[d>>2]=0,1;case 12351:return x[d>>2]=12430,1;case 12352:return x[d>>2]=4,1;case 12354:return x[d>>2]=0,1;default:return L=12292,0}},K:function(){L=12288;return 62E3},
ua:function(){return L},Ga:function(a,b,c){if(62E3!=a)return L=12296,0;b&&(x[b>>2]=1);c&&(x[c>>2]=4);Gb=!0;L=12288;return 1},Aa:function(a,b,c,d){if(62E3!=a)return L=12296,0;if(0!=d&&62004!=d)return L=12294,0;if(0!=c&&62006!=c||0!=b&&62006!=b)return L=12301,0;wb(d?Lb:null);Hb=d;Jb=b;Ib=c;L=12288;return 1},ta:function(a,b){if(62E3!=a)return L=12296,0;L=12288;if(Kb[b])return Kb[b];switch(b){case 12371:a=S("Emscripten");break;case 12372:a=S("1.4 Emscripten EGL");break;case 12373:a=S("");break;case 12429:a=
S("OpenGL_ES");break;default:return L=12300,0}return Kb[b]=a},Ba:function(){if(Gb)if(h.fe)if(h.fe.isContextLost())L=12302;else return L=12288,1;else L=12290;else L=12289;return 0},Ca:function(a,b){if(62E3!=a)return L=12296,0;0==b?Oa(0,0):Oa(1,b);L=12288;return 1},Ha:function(a){if(62E3!=a)return L=12296,0;Jb=Ib=Hb=0;Gb=!1;L=12288;return 1},Ea:function(){L=12288;return 1},Da:function(){L=12288;return 1},Ma:function(a,b,c){b=dc(b,c);return Ha[a].apply(null,b)},a:function(a,b,c){b=dc(b,c);return Ha[a].apply(null,
b)},T:function(){return Date.now()},oa:function(){if(!qc())return-1;lc(Oc);var a=Fc[1];if(a.exitFullscreen)a.fullscreenElement&&a.exitFullscreen();else if(a.webkitExitFullscreen)a.webkitFullscreenElement&&a.webkitExitFullscreen();else return-1;return 0},ra:function(){lc(Pc);if(document.exitPointerLock)document.exitPointerLock();else return-1;return 0},d:function(){return devicePixelRatio},b:function(a,b,c){a=W(a);if(!a)return-4;a=Nc(a);A[b>>3]=a.width;A[c>>3]=a.height;return 0},N:function(a,b){if(0>
a||a>=sc.length)return-5;if(!sc[a])return-7;Qc(b,sc[a]);return 0},l:Ua,La:function(){return sc.length},sa:function(a,b){x[a>>2]=screen.width;x[b>>2]=screen.height},Nd:function(a){K.activeTexture(a)},Md:Rc,ka:function(a,b){K.ge.beginQueryEXT(a,Q[b])},Ld:function(a,b,c){K.bindAttribLocation(O[a],b,F(c))},Kd:Sc,Jd:function(a,b){K.bindFramebuffer(a,Rb[b])},Id:function(a,b){K.bindRenderbuffer(a,Sb[b])},Hd:function(a,b){K.bindTexture(a,Tb[b])},ba:function(a){K.bindVertexArray(Ub[a])},Gd:function(a,b,c,
d){K.blendColor(a,b,c,d)},Ed:function(a){K.blendEquation(a)},Dd:function(a,b){K.blendEquationSeparate(a,b)},Cd:function(a,b){K.blendFunc(a,b)},Bd:function(a,b,c,d){K.blendFuncSeparate(a,b,c,d)},Ad:Tc,zd:function(a,b,c,d){K.bufferSubData(a,b,w.subarray(d,d+c))},yd:function(a){return K.checkFramebufferStatus(a)},xd:Uc,wd:Vc,vd:function(a){K.clearDepth(a)},td:function(a){K.clearStencil(a)},sd:function(a,b,c,d){K.colorMask(!!a,!!b,!!c,!!d)},rd:Wc,qd:function(a,b,c,d,e,g,f,m){K.compressedTexImage2D(a,
b,c,d,e,g,m?w.subarray(m,m+f):null)},pd:function(a,b,c,d,e,g,f,m,n){K.compressedTexSubImage2D(a,b,c,d,e,g,f,n?w.subarray(n,n+m):null)},od:function(a,b,c,d,e,g,f,m){K.copyTexImage2D(a,b,c,d,e,g,f,m)},nd:function(a,b,c,d,e,g,f,m){K.copyTexSubImage2D(a,b,c,d,e,g,f,m)},md:Xc,ld:Yc,kd:function(a){K.cullFace(a)},jd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Qb[d];e&&(K.deleteBuffer(e),e.name=0,Qb[d]=null)}},id:function(a,b){for(var c=0;c<a;++c){var d=x[b+4*c>>2],e=Rb[d];e&&(K.deleteFramebuffer(e),
e.name=0,Rb[d]=null)}},hd:Zc,ma:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Q[d];e&&(K.ge.deleteQueryEXT(e),Q[d]=null)}},gd:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Sb[d];e&&(K.deleteRenderbuffer(e),e.name=0,Sb[d]=null)}},fd:function(a){if(a){var b=P[a];b?(K.deleteShader(b),P[a]=null):R(1281)}},ed:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2],e=Tb[d];e&&(K.deleteTexture(e),e.name=0,Tb[d]=null)}},aa:function(a,b){for(var c=0;c<a;c++){var d=x[b+4*c>>2];K.deleteVertexArray(Ub[d]);
Ub[d]=null}},dd:function(a){K.depthFunc(a)},cd:function(a){K.depthMask(!!a)},bd:function(a,b){K.depthRange(a,b)},ad:function(a,b){K.detachShader(O[a],P[b])},_c:function(a){K.disable(a)},Zc:function(a){K.disableVertexAttribArray(a)},Yc:function(a,b,c){K.drawArrays(a,b,c)},Y:function(a,b,c,d){K.drawArraysInstanced(a,b,c,d)},Z:function(a,b){for(var c=$c[a],d=0;d<a;d++)c[d]=x[b+4*d>>2];K.drawBuffers(c)},Xc:ad,Pd:function(a,b,c,d,e){K.drawElementsInstanced(a,b,c,d,e)},Wc:bd,Vc:cd,ja:function(a){K.ge.endQueryEXT(a)},
Uc:function(){K.finish()},Tc:function(){K.flush()},Sc:function(a,b,c,d){K.framebufferRenderbuffer(a,b,c,Sb[d])},Rc:function(a,b,c,d,e){K.framebufferTexture2D(a,b,c,Tb[d],e)},Pc:function(a){K.frontFace(a)},Oc:ed,Mc:function(a,b){dd(a,b,"createFramebuffer",Rb)},na:function(a,b){for(var c=0;c<a;c++){var d=K.ge.createQueryEXT();if(!d){for(R(1282);c<a;)x[b+4*c++>>2]=0;break}var e=Yb(Q);d.name=e;Q[e]=d;x[b+4*c>>2]=e}},Lc:function(a,b){dd(a,b,"createRenderbuffer",Sb)},Kc:function(a,b){dd(a,b,"createTexture",
Tb)},$:function(a,b){dd(a,b,"createVertexArray",Ub)},Nc:function(a){K.generateMipmap(a)},Jc:function(a,b,c,d,e,g,f){fd("getActiveAttrib",a,b,c,d,e,g,f)},Ic:function(a,b,c,d,e,g,f){fd("getActiveUniform",a,b,c,d,e,g,f)},Hc:function(a,b,c,d){a=K.getAttachedShaders(O[a]);var e=a.length;e>b&&(e=b);x[c>>2]=e;for(b=0;b<e;++b)x[d+4*b>>2]=P.indexOf(a[b])},Gc:gd,Fc:function(a,b){jd(a,b,4)},Ec:function(a,b,c){c?x[c>>2]=K.getBufferParameter(a,b):R(1281)},Dc:function(){var a=K.getError()||Xb;Xb=0;return a},Cc:function(a,
b){jd(a,b,2)},Bc:function(a,b,c,d){a=K.getFramebufferAttachmentParameter(a,b,c);if(a instanceof WebGLRenderbuffer||a instanceof WebGLTexture)a=a.name|0;x[d>>2]=a},Ac:function(a,b){jd(a,b,0)},yc:kd,zc:ld,da:md,fa:nd,ca:md,ea:nd,ha:function(a,b,c){c?x[c>>2]=K.ge.getQueryEXT(a,b):R(1281)},xc:function(a,b,c){c?x[c>>2]=K.getRenderbufferParameter(a,b):R(1281)},vc:function(a,b,c,d){a=K.getShaderInfoLog(P[a]);null===a&&(a="(unknown error)");b=0<b&&d?E(a,d,b):0;c&&(x[c>>2]=b)},uc:function(a,b,c,d){a=K.getShaderPrecisionFormat(a,
b);x[c>>2]=a.rangeMin;x[c+4>>2]=a.rangeMax;x[d>>2]=a.precision},tc:function(a,b,c,d){if(a=K.getShaderSource(P[a]))b=0<b&&d?E(a,d,b):0,c&&(x[c>>2]=b)},wc:function(a,b,c){c?35716==b?(a=K.getShaderInfoLog(P[a]),null===a&&(a="(unknown error)"),x[c>>2]=a?a.length+1:0):35720==b?(a=K.getShaderSource(P[a]),x[c>>2]=a?a.length+1:0):x[c>>2]=K.getShaderParameter(P[a],b):R(1281)},sc:function(a){var b=Vb[a];if(!b){switch(a){case 7939:b=K.getSupportedExtensions()||[];b=b.concat(b.map(function(d){return"GL_"+d}));
b=S(b.join(" "));break;case 7936:case 7937:case 37445:case 37446:(b=K.getParameter(a))||R(1280);b=b&&S(b);break;case 7938:b=S("OpenGL ES 2.0 ("+K.getParameter(7938)+")");break;case 35724:b=K.getParameter(35724);var c=b.match(/^WebGL GLSL ES ([0-9]\.[0-9][0-9]?)(?:$| .*)/);null!==c&&(3==c[1].length&&(c[1]+="0"),b="OpenGL ES GLSL ES "+c[1]+" ("+b+")");b=S(b);break;default:R(1280)}Vb[a]=b}return b},rc:function(a,b,c){c?z[c>>2]=K.getTexParameter(a,b):R(1281)},qc:function(a,b,c){c?x[c>>2]=K.getTexParameter(a,
b):R(1281)},nc:qd,pc:function(a,b,c){rd(a,b,c,2)},oc:function(a,b,c){rd(a,b,c,0)},jc:function(a,b,c){c?x[c>>2]=K.getVertexAttribOffset(a,b):R(1281)},mc:function(a,b,c){sd(a,b,c,2)},kc:function(a,b,c){sd(a,b,c,5)},ic:function(a,b){K.hint(a,b)},hc:function(a){return(a=Qb[a])?K.isBuffer(a):0},gc:function(a){return K.isEnabled(a)},fc:function(a){return(a=Rb[a])?K.isFramebuffer(a):0},ec:function(a){return(a=O[a])?K.isProgram(a):0},la:function(a){return(a=Q[a])?K.ge.isQueryEXT(a):0},dc:function(a){return(a=
Sb[a])?K.isRenderbuffer(a):0},cc:function(a){return(a=P[a])?K.isShader(a):0},bc:function(a){return(a=Tb[a])?K.isTexture(a):0},_:function(a){return(a=Ub[a])?K.isVertexArray(a):0},$b:function(a){K.lineWidth(a)},_b:td,Zb:function(a,b){3317==a&&(Wb=b);K.pixelStorei(a,b)},Yb:function(a,b){K.polygonOffset(a,b)},ia:function(a,b){K.ge.queryCounterEXT(Q[a],b)},Xb:function(a,b,c,d,e,g,f){(f=ud(g,e,c,d,f))?K.readPixels(a,b,c,d,e,g,f):R(1280)},Wb:function(){},Vb:function(a,b,c,d){K.renderbufferStorage(a,b,c,
d)},Ub:function(a,b){K.sampleCoverage(a,!!b)},Tb:function(a,b,c,d){K.scissor(a,b,c,d)},Sb:function(){R(1280)},Rb:vd,Qb:function(a,b,c){K.stencilFunc(a,b,c)},Pb:function(a,b,c,d){K.stencilFuncSeparate(a,b,c,d)},Ob:function(a){K.stencilMask(a)},Nb:function(a,b){K.stencilMaskSeparate(a,b)},Mb:function(a,b,c){K.stencilOp(a,b,c)},Lb:function(a,b,c,d){K.stencilOpSeparate(a,b,c,d)},Kb:function(a,b,c,d,e,g,f,m,n){K.texImage2D(a,b,c,d,e,g,f,m,n?ud(m,f,d,e,n):null)},Jb:function(a,b,c){K.texParameterf(a,b,c)},
Ib:function(a,b,c){K.texParameterf(a,b,z[c>>2])},Gb:function(a,b,c){K.texParameteri(a,b,c)},Fb:function(a,b,c){K.texParameteri(a,b,x[c>>2])},Eb:function(a,b,c,d,e,g,f,m,n){var r=null;n&&(r=ud(m,f,e,g,n));K.texSubImage2D(a,b,c,d,e,g,f,m,r)},Db:wd,Cb:function(a,b,c){if(288>=b)for(var d=Y[b-1],e=0;e<b;++e)d[e]=z[c+4*e>>2];else d=z.subarray(c>>2,c+4*b>>2);K.uniform1fv(X(a),d)},Bb:function(a,b){K.uniform1i(X(a),b)},Ab:function(a,b,c){if(288>=b)for(var d=xd[b-1],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>
2,c+4*b>>2);K.uniform1iv(X(a),d)},zb:function(a,b,c){K.uniform2f(X(a),b,c)},yb:function(a,b,c){if(144>=b)for(var d=Y[2*b-1],e=0;e<2*b;e+=2)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2];else d=z.subarray(c>>2,c+8*b>>2);K.uniform2fv(X(a),d)},xb:function(a,b,c){K.uniform2i(X(a),b,c)},wb:function(a,b,c){if(144>=b)for(var d=xd[2*b-1],e=0;e<2*b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2];else d=x.subarray(c>>2,c+8*b>>2);K.uniform2iv(X(a),d)},vb:yd,ub:function(a,b,c){if(96>=b)for(var d=Y[3*b-1],e=0;e<3*b;e+=
3)d[e]=z[c+4*e>>2],d[e+1]=z[c+(4*e+4)>>2],d[e+2]=z[c+(4*e+8)>>2];else d=z.subarray(c>>2,c+12*b>>2);K.uniform3fv(X(a),d)},tb:function(a,b,c,d){K.uniform3i(X(a),b,c,d)},sb:function(a,b,c){if(96>=b)for(var d=xd[3*b-1],e=0;e<3*b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2];else d=x.subarray(c>>2,c+12*b>>2);K.uniform3iv(X(a),d)},rb:function(a,b,c,d,e){K.uniform4f(X(a),b,c,d,e)},qb:function(a,b,c){if(72>=b){var d=Y[4*b-1],e=z;c>>=2;for(var g=0;g<4*b;g+=4){var f=c+g;d[g]=e[f];d[g+
1]=e[f+1];d[g+2]=e[f+2];d[g+3]=e[f+3]}}else d=z.subarray(c>>2,c+16*b>>2);K.uniform4fv(X(a),d)},pb:function(a,b,c,d,e){K.uniform4i(X(a),b,c,d,e)},ob:function(a,b,c){if(72>=b)for(var d=xd[4*b-1],e=0;e<4*b;e+=4)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2],d[e+3]=x[c+(4*e+12)>>2];else d=x.subarray(c>>2,c+16*b>>2);K.uniform4iv(X(a),d)},nb:function(a,b,c,d){if(72>=b)for(var e=Y[4*b-1],g=0;g<4*b;g+=4)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2];
else e=z.subarray(d>>2,d+16*b>>2);K.uniformMatrix2fv(X(a),!!c,e)},mb:function(a,b,c,d){if(32>=b)for(var e=Y[9*b-1],g=0;g<9*b;g+=9)e[g]=z[d+4*g>>2],e[g+1]=z[d+(4*g+4)>>2],e[g+2]=z[d+(4*g+8)>>2],e[g+3]=z[d+(4*g+12)>>2],e[g+4]=z[d+(4*g+16)>>2],e[g+5]=z[d+(4*g+20)>>2],e[g+6]=z[d+(4*g+24)>>2],e[g+7]=z[d+(4*g+28)>>2],e[g+8]=z[d+(4*g+32)>>2];else e=z.subarray(d>>2,d+36*b>>2);K.uniformMatrix3fv(X(a),!!c,e)},lb:zd,kb:Ad,jb:function(a){K.validateProgram(O[a])},ib:function(a,b){K.vertexAttrib1f(a,b)},hb:function(a,
b){K.vertexAttrib1f(a,z[b>>2])},gb:function(a,b,c){K.vertexAttrib2f(a,b,c)},fb:function(a,b){K.vertexAttrib2f(a,z[b>>2],z[b+4>>2])},eb:function(a,b,c,d){K.vertexAttrib3f(a,b,c,d)},db:function(a,b){K.vertexAttrib3f(a,z[b>>2],z[b+4>>2],z[b+8>>2])},bb:function(a,b,c,d,e){K.vertexAttrib4f(a,b,c,d,e)},ab:function(a,b){K.vertexAttrib4f(a,z[b>>2],z[b+4>>2],z[b+8>>2],z[b+12>>2])},Od:function(a,b){K.vertexAttribDivisor(a,b)},$a:Bd,_a:Cd,j:function(){return 0},Za:function(a,b,c){w.copyWithin(a,b,b+c)},pa:function(a,
b,c){return Dd(a,{we:x[c>>2],ue:x[c+4>>2],Te:x[c+8>>2],Qe:b,oe:x[c+12>>2],Ae:x[c+16>>2]})},J:function(a,b){a=W(a);return a?a.requestPointerLock?hc&&nc.je?Pc(a):b?(kc(Pc,2,[a]),1):-2:-1:-4},Ra:function(){p("OOM")},lc:function(a){eval(F(a))},O:function(){return(sc=navigator.getGamepads?navigator.getGamepads():navigator.webkitGetGamepads?navigator.webkitGetGamepads():null)?0:-1},o:function(a,b,c){if("undefined"==typeof onbeforeunload)return-1;if(1!==c)return-5;Ed(a,b);return 0},A:function(a,b,c,d){Fd(a,
b,c,d,12,"blur");return 0},c:Jc,h:function(a,b,c){a=W(a);if(!a)return-4;a.style.width=b+"px";a.style.height=c+"px";return 0},B:function(a,b,c,d){Fd(a,b,c,d,13,"focus");return 0},q:function(a,b,c,d){if(!qc())return-1;a=W(a);if(!a)return-4;Gd(a,b,c,d,"fullscreenchange");Gd(a,b,c,d,"webkitfullscreenchange");return 0},M:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;Hd(a,b,c,26,"gamepadconnected");return 0},L:function(a,b,c){if(!navigator.getGamepads&&!navigator.webkitGetGamepads)return-1;
Hd(a,b,c,27,"gamepaddisconnected");return 0},t:function(a,b,c,d){Id(a,b,c,d,2,"keydown");return 0},r:function(a,b,c,d){Id(a,b,c,d,1,"keypress");return 0},s:function(a,b,c,d){Id(a,b,c,d,3,"keyup");return 0},Na:function(a,b,c){a=G(a);Xa(a,b,c)},G:function(a,b,c,d){Kd(a,b,c,d,5,"mousedown");return 0},E:function(a,b,c,d){Kd(a,b,c,d,33,"mouseenter");return 0},D:function(a,b,c,d){Kd(a,b,c,d,34,"mouseleave");return 0},H:function(a,b,c,d){Kd(a,b,c,d,8,"mousemove");return 0},F:function(a,b,c,d){Kd(a,b,c,d,
6,"mouseup");return 0},u:function(a,b,c,d){if(!document||!document.body||!(document.body.requestPointerLock||document.body.ne||document.body.Ke||document.body.Je))return-1;a=W(a);if(!a)return-4;Ld(a,b,c,d,"pointerlockchange");Ld(a,b,c,d,"mozpointerlockchange");Ld(a,b,c,d,"webkitpointerlockchange");Ld(a,b,c,d,"mspointerlockchange");return 0},k:function(a,b,c,d){Md(a,b,c,d);return 0},v:function(a,b,c,d){Nd(a,b,c,d,25,"touchcancel");return 0},x:function(a,b,c,d){Nd(a,b,c,d,23,"touchend");return 0},w:function(a,
b,c,d){Nd(a,b,c,d,24,"touchmove");return 0},z:function(a,b,c,d){Nd(a,b,c,d,22,"touchstart");return 0},p:function(a,b,c){Od(a,b,c);return 0},C:function(a,b,c,d){a=W(a);return"undefined"!=typeof a.onwheel?(Pd(a,b,c,d),0):-1},qa:function(a){ea(F(a))},i:function(){throw"Please compile your program with async support in order to use asynchronous operations like emscripten_sleep";},Sa:function(a,b){var c=0;Rd().forEach(function(d,e){var g=b+c;e=y[a+4*e>>2]=g;for(g=0;g<d.length;++g)u[e++>>0]=d.charCodeAt(g);
u[e>>0]=0;c+=d.length+1});return 0},Ta:function(a,b){var c=Rd();y[a>>2]=c.length;var d=0;c.forEach(function(e){d+=e.length+1});y[b>>2]=d;return 0},Q:function(){return 52},Ua:function(){return 52},Qa:function(){return 70},R:function(a,b,c,d){for(var e=0,g=0;g<c;g++){var f=y[b>>2],m=y[b+4>>2];b+=8;for(var n=0;n<m;n++){var r=w[f+n],t=Yd[a];0===r||10===r?((1===a?fa:l)(Na(t,0)),t.length=0):t.push(r)}e+=m}y[d>>2]=e;return 0},W:Rc,g:Sc,V:Tc,ac:Uc,cb:Vc,n:Wc,ga:Xc,I:Yc,za:Zc,Hb:ad,U:bd,Oa:cd,X:ed,ud:gd,Ja:kd,
P:ld,e:qd,Fd:td,y:vd,Wa:wd,f:yd,m:zd,$c:Ad,Pa:Bd,Qc:Cd};
(function(){function a(c){c=c.exports;h.asm=c;ia=h.asm.Qd;var d=ia.buffer;h.HEAP8=u=new Int8Array(d);h.HEAP16=ka=new Int16Array(d);h.HEAP32=x=new Int32Array(d);h.HEAPU8=w=new Uint8Array(d);h.HEAPU16=la=new Uint16Array(d);h.HEAPU32=y=new Uint32Array(d);h.HEAPF32=z=new Float32Array(d);h.HEAPF64=A=new Float64Array(d);ma=h.asm.Ud;oa.unshift(h.asm.Rd);B--;h.monitorRunDependencies&&h.monitorRunDependencies(B);0==B&&(null!==ua&&(clearInterval(ua),ua=null),va&&(d=va,va=null,d()));return c}var b={a:ae};B++;
h.monitorRunDependencies&&h.monitorRunDependencies(B);if(h.instantiateWasm)try{return h.instantiateWasm(b,a)}catch(c){return l("Module.instantiateWasm callback failed with error: "+c),!1}Ba(b,function(c){a(c.instance)});return{}})();function D(){return(D=h.asm.Sd).apply(null,arguments)}var be=h._main=function(){return(be=h._main=h.asm.Td).apply(null,arguments)};function fc(){return(fc=h.asm.Vd).apply(null,arguments)}function gc(){return(gc=h.asm.Wd).apply(null,arguments)}
function Hc(){return(Hc=h.asm.Xd).apply(null,arguments)}h.dynCall_jiji=function(){return(h.dynCall_jiji=h.asm.Yd).apply(null,arguments)};h.dynCall_ji=function(){return(h.dynCall_ji=h.asm.Zd).apply(null,arguments)};var ce;va=function de(){ce||ee();ce||(va=de)};function fe(a=[]){var b=be;a.unshift(ca);var c=a.length,d=Hc(4*(c+1)),e=d>>2;a.forEach(f=>{x[e++]=Gc(f)});x[e]=0;try{var g=b(c,d);fb(g)}catch(f){eb(f)}}
function ee(){var a=ba;function b(){if(!ce&&(ce=!0,h.calledRun=!0,!q)){Ka(oa);Ka(qa);if(h.onRuntimeInitialized)h.onRuntimeInitialized();ge&&fe(a);if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();sa.unshift(c)}Ka(sa)}}if(!(0<B)){if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ta();Ka(na);0<B||(h.setStatus?(h.setStatus("Running..."),setTimeout(function(){setTimeout(function(){h.setStatus("")},1);b()},
1)):b())}}if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.pop()();var ge=!0;h.noInitialRun&&(ge=!1);ee();
